### ISSUE TITLE
stable branch needs to be updated with 98da440

### ISSUE THREAD

**Issue by grahamb** [instructure/analytics#10]
The `master` branch contains a commit (98da4407) to add a `version` property to package.json so that it can be used with yarn workspaces in Canvas. This commit is missing from the `stable` branch, so Canvas installations that pull from `stable` instead of `master` can't build.

Steps to reproduce:
1. Clone canvas-lms/stable
2. Clone analytics/stable into gems/plugins/analytics
3. bundle install, yarn install
4. bundle exec rake canvas:compile_assets

Expected behaviour
- Canvas should build

Actual behaviour
- `yarn` will throw a warning and not install the analytics gem's dependencies: `warning Missing version in workspace at "/path/to/canvas/gems/plugins/analytics", ignoring.`. Later on, the webpack build will fail because of missing dependencies in analytics:

```
ERROR in ./gems/plugins/analytics/app/coffeescripts/graphs/base.coffee
    Module not found: Error: Can't resolve 'graphael' in '/path/to/canvas/gems/plugins/analytics/app/coffeescripts/graphs'
	 @ ./gems/plugins/analytics/app/coffeescripts/graphs/base.coffee 1:0-207:2
	 @ ./gems/plugins/analytics/app/coffeescripts/graphs/grades.coffee
	 @ ./gems/plugins/analytics/app/coffeescripts/Course/CourseView.coffee
	 @ ./gems/plugins/analytics/app/coffeescripts/bundles/course.coffee
```

**Comment by ccutrer** [comment]
Stable branch updated.
