### ISSUE TITLE
uninitialized constant Analytics::Engine::AccountServices

### ISSUE THREAD

**Issue by arunkumargit** [instructure/analytics#5]
when I run `RAILS_ENV=production bundle exec rake db:migrate`
rake aborted!
NameError: uninitialized constant Analytics::Engine::AccountServices
/var/canvas/gems/plugins/analytics/lib/analytics/engine.rb:37:in `<class:Engine>'
/var/canvas/gems/plugins/analytics/lib/analytics/engine.rb:20:in `<module:Analytics>'
/var/canvas/gems/plugins/analytics/lib/analytics/engine.rb:19:in `<top (required)>'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/canvas/vendor/bundle/ruby/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/var/canvas/gems/plugins/analytics/lib/analytics.rb:19:in `<top (required)>'
/var/lib/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
/var/lib/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
/var/lib/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `block in require'
/var/lib/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
/var/lib/gems/2.1.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
/var/lib/gems/2.1.0/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
/var/canvas/config/application.rb:13:in `<top (required)>'
/var/canvas/Rakefile:4:in `require'

**Using Analytics and Canvas release of March 2014.**

**Comment by ccutrer** [comment]
Can you confirm that lib/account_services.rb exists in your Canvas install?

**Comment by arunkumargit** [comment]
@ccutrer lib/account_services.rb doesn't exist in my canvas.

**Comment by ccutrer** [comment]
That file was created in April 2015 in Canvas. So you're using a release of analytics newer than that, but a Canvas older than that. I can't remember when analytics was open sourced, but I believe it was after March 2014. So you'll need to update Canvas.
